import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { MapPin, Plus, Trash2, Factory, LayoutList, Package, BookOpen, Truck, Music2, Briefcase, type LucideIcon } from 'lucide-react';
import { zonesApi } from '../lib/api';
import { useZoneTypes } from '../lib/useZoneTypes';
import type { Zone } from '../lib/api';

export function ZonesPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [zones, setZones] = useState<Zone[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    type: 'warehouse',
    description: '',
    capacity: '',
    parent_zone_id: searchParams.get('parent') || '',
  });
  const { zoneTypes: zoneTypeDefs, loading: zoneTypesLoading } = useZoneTypes();

  useEffect(() => {
    loadZones();
  }, []);

  const loadZones = async () => {
    try {
      const { data } = await zonesApi.getAll();
      setZones(data);
    } catch (error) {
      console.error('Failed to load zones:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // Open form if parent_zone_id is in URL
    if (searchParams.get('parent')) {
      setShowForm(true);
    }
  }, [searchParams]);

  const iconMap: Record<string, LucideIcon> = useMemo(() => ({
    warehouse: Factory,
    rack: LayoutList,
    gitterbox: Package,
    shelf: BookOpen,
    vehicle: Truck,
    stage: Music2,
    case: Briefcase,
    other: MapPin,
  }), []);

  const zoneTypeOptions = useMemo(
    () =>
      zoneTypeDefs.map((type) => ({
        value: type.key,
        label: type.label,
        icon: iconMap[type.key] || iconMap.other,
        description: type.description,
      })),
    [zoneTypeDefs, iconMap]
  );

  useEffect(() => {
    if (zoneTypeOptions.length === 0) {
      return;
    }

    setFormData((prev) => {
      if (zoneTypeOptions.some((type) => type.value === prev.type)) {
        return prev;
      }
      return { ...prev, type: zoneTypeOptions[0].value };
    });
  }, [zoneTypeOptions]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const payload: any = {
        name: formData.name,
        type: formData.type,
        description: formData.description || undefined,
        capacity: formData.capacity ? parseInt(formData.capacity) : undefined,
        parent_zone_id: formData.parent_zone_id ? parseInt(formData.parent_zone_id) : undefined,
        is_active: true,
      };
      // code will be auto-generated by backend
      await zonesApi.create(payload);
      setShowForm(false);
      const fallbackType = zoneTypeOptions[0]?.value || 'warehouse';
      setFormData({ name: '', type: fallbackType, description: '', capacity: '', parent_zone_id: '' });
      loadZones();

      // If we created a subzone, navigate back to parent zone detail
      if (formData.parent_zone_id) {
        navigate(`/zones/${formData.parent_zone_id}`);
      } else {
        navigate('/zones');
      }
    } catch (error) {
      console.error('Failed to create zone:', error);
    }
  };

  const handleZoneClick = (zoneId: number) => {
    navigate(`/zones/${zoneId}`);
  };

  const handleDeleteZone = async (e: React.MouseEvent, zone: Zone) => {
    e.stopPropagation(); // Prevent navigation when clicking delete

    if (!confirm(`Zone "${zone.name}" (${zone.code}) wirklich löschen?`)) {
      return;
    }

    try {
      await zonesApi.delete(zone.zone_id);
      loadZones();
    } catch (error) {
      console.error('Failed to delete zone:', error);
      alert('Fehler beim Löschen der Zone. Prüfe ob die Zone Unterzonen oder Geräte enthält.');
    }
  };

  // Get parent zone name if creating subzone
  const parentZone = formData.parent_zone_id
    ? zones.find((z) => z.zone_id === parseInt(formData.parent_zone_id))
    : null;

  // Filter root zones (no parent) for main view
  const rootZones = zones.filter((z) => !z.parent_zone_id);

  if (loading || zoneTypesLoading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div
          className="rounded-full h-10 w-10 border-2 border-t-transparent animate-spin"
          style={{ borderColor: 'var(--border-subtle)', borderTopColor: 'var(--accent-red)' }}
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-bold text-white mb-1" style={{ fontSize: '1.75rem' }}>Lager</h2>
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{rootZones.length} Hauptzonen · {zones.length} gesamt</p>
        </div>
        <button
          onClick={() => setShowForm(!showForm)}
          className="flex items-center gap-2 font-semibold rounded-lg cursor-pointer transition-all"
          style={{
            padding: '0.625rem 1.25rem',
            background: 'var(--accent-red)',
            color: 'var(--text-primary)',
            border: 'none',
            fontSize: '0.9375rem',
            boxShadow: 'var(--shadow-accent)',
          }}
        >
          <Plus className="w-4 h-4" />
          {parentZone ? 'Unterzone erstellen' : 'Zone erstellen'}
        </button>
      </div>

      {/* Create Form */}
      {showForm && (
        <div className="card p-6" style={{ borderColor: 'rgba(var(--accent-red-rgb), 0.2)' }}>
          <h3 className="font-semibold text-white mb-5" style={{ fontSize: '1rem' }}>
            {parentZone ? `Unterzone in ${parentZone.name} erstellen` : 'Neue Zone erstellen'}
          </h3>
          {parentZone && (
            <div
              className="mb-4 px-4 py-3 rounded-lg text-sm"
              style={{ background: 'var(--bg-subtle)', color: 'var(--text-secondary)' }}
            >
              Übergeordnete Zone: <span className="text-white font-medium">{parentZone.name}</span> ({parentZone.code})
            </div>
          )}
          <form onSubmit={handleSubmit} className="space-y-3">
            {formData.type === 'shelf' && (
              <div
                className="px-4 py-3 rounded-lg text-sm"
                style={{ background: 'rgba(var(--color-info-rgb), 0.08)', border: '1px solid rgba(var(--color-info-rgb), 0.2)', color: 'var(--color-info)' }}
              >
                Name und Barcode werden automatisch generiert (Fach 01, Fach 02, ...)
              </div>
            )}
            {formData.type !== 'shelf' && (
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="Name (z.B. Lager Weidelbach, Regal A1)"
                required
                className="w-full px-4 py-3"
              />
            )}
            <select
              value={formData.type}
              onChange={(e) => setFormData({ ...formData, type: e.target.value })}
              className="w-full px-4 py-3"
              disabled={zoneTypeOptions.length === 0}
            >
              {zoneTypeOptions.map((type) => (
                <option key={type.value} value={type.value}>
                  {type.label}
                </option>
              ))}
            </select>
            <input
              type="number"
              value={formData.capacity}
              onChange={(e) => setFormData({ ...formData, capacity: e.target.value })}
              placeholder="Kapazität (optional)"
              className="w-full px-4 py-3"
            />
            <textarea
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Beschreibung (optional)"
              rows={3}
              className="w-full px-4 py-3 resize-none"
            />
            <div className="flex gap-3 pt-1">
              <button
                type="submit"
                className="flex-1 py-3 font-semibold rounded-lg cursor-pointer transition-colors"
                style={{ background: 'var(--accent-red)', color: 'var(--text-primary)', border: 'none' }}
              >
                Erstellen
              </button>
              <button
                type="button"
                onClick={() => setShowForm(false)}
                className="px-5 py-3 font-medium rounded-lg cursor-pointer transition-colors"
                style={{
                  background: 'var(--bg-subtle)',
                  color: 'var(--text-secondary)',
                  border: '1px solid var(--border-subtle)',
                }}
              >
                Abbrechen
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Zones Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {rootZones.map((zone) => {
          const typeInfo = zoneTypeOptions.find((t) => t.value === zone.type);
          const ZoneIcon = typeInfo?.icon ?? iconMap.other;
          return (
            <div
              key={zone.zone_id}
              className="card p-5 cursor-pointer group relative transition-all duration-200"
              style={{ borderColor: 'var(--border-subtle)' }}
              onClick={() => handleZoneClick(zone.zone_id)}
              onMouseEnter={(e) => (e.currentTarget.style.borderColor = 'rgba(var(--accent-red-rgb), 0.3)')}
              onMouseLeave={(e) => (e.currentTarget.style.borderColor = 'var(--border-subtle)')}
            >
              <button
                onClick={(e) => handleDeleteZone(e, zone)}
                className="absolute top-3 right-3 p-1.5 rounded-lg opacity-0 group-hover:opacity-100 transition-all cursor-pointer"
                style={{ background: 'rgba(var(--accent-red-rgb), 0.1)', color: 'var(--accent-red-light)', border: '1px solid rgba(var(--accent-red-rgb), 0.2)' }}
                title="Zone löschen"
              >
                <Trash2 className="w-3.5 h-3.5" />
              </button>
              <div className="flex items-start gap-4">
                <div
                  className="inline-flex items-center justify-center w-10 h-10 rounded-lg flex-shrink-0"
                  style={{ background: 'var(--bg-subtle)' }}
                >
                  <ZoneIcon className="w-5 h-5" style={{ color: 'var(--text-secondary)' }} />
                </div>
                <div className="flex-1 min-w-0 pr-6">
                  <h3 className="font-semibold text-white truncate mb-0.5 transition-colors group-hover:text-red-400">
                    {zone.name}
                  </h3>
                  <p className="text-xs mb-2 font-mono" style={{ color: 'var(--text-tertiary)' }}>{zone.code}</p>
                  <div className="flex items-center gap-2 text-xs" style={{ color: 'var(--text-tertiary)' }}>
                    <span>{typeInfo?.label || zone.type}</span>
                    {zone.capacity && (
                      <>
                        <span>·</span>
                        <span>Kap. {zone.capacity}</span>
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {rootZones.length === 0 && !showForm && (
        <div className="text-center py-16">
          <div
            className="inline-flex items-center justify-center w-16 h-16 rounded-2xl mb-4"
            style={{ background: 'var(--bg-subtle)', border: '1px solid var(--border-subtle)' }}
          >
            <MapPin className="w-8 h-8" style={{ color: 'var(--text-tertiary)' }} />
          </div>
          <p className="mb-4 text-sm" style={{ color: 'var(--text-secondary)' }}>Noch keine Lagerorte vorhanden</p>
          <button
            onClick={() => setShowForm(true)}
            className="text-sm font-semibold cursor-pointer transition-colors"
            style={{ color: 'var(--accent-red)', background: 'none', border: 'none' }}
          >
            Erste Zone erstellen
          </button>
        </div>
      )}
    </div>
  );
}
